archives:
- id: goimports
  files:
  - LICENSE
  - PATENTS
  format: tar.gz
  name_template: "{{.Binary}}_{{.Version}}_{{.Os}}-{{.Arch}}"
  replacements:
    386:    32bit
    amd64:  64bit
    darwin: macOS
    linux:  Linux

brews:
- name: goimports
  description: |
    Command goimports updates your Go import lines,
    adding missing ones and removing unreferenced ones.
    In addition to fixing imports, goimports also formats
    your code in the same style as gofmt so it can be used
    as a replacement for your editor's gofmt-on-save hook.
  homepage: https://github.com/kamilsk/go-tools
  commit_author:
    name:  Kamil Samigullin
    email: kamil@samigullin.info
  folder: Formula
  github:
    name:  homebrew-tap
    owner: kamilsk

builds:
- binary: goimports
  env:
  - CGO_ENABLED=0
  goarch:
  - 386
  - amd64
  goos:
  - darwin
  - linux
  main: ./cmd/goimports

changelog: { skip: true }

checksum: { name_template: checksums.txt }

release:
  draft: false
  github:
    name:  go-tools
    owner: kamilsk
